<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 ./DamagedHelmet.glb -t
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      ['node_damagedHelmet_-6514']: THREE.Mesh
    }
    materials: {
      Material_MR: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/DamagedHelmet.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes['node_damagedHelmet_-6514'].geometry}
      material={gltf.materials.Material_MR}
      
      rotation={[8, 0, 0]}
      material.envMapIntensity={0.8}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
